[package]
name = "state"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
aper = {git = "https://github.com/aper-dev/aper.git"}
rand = "0.8"
rand_chacha = {version = "0.3", features = ["serde1"]}
uuid = "*"
